FORMAT: 1A

# AMP-epsilon
API Endpoint: http://52.74.60.142/api/

All api datetime format (Timezone: +00:00): **YYYY-MM-DDThh:mm:ssTZD** (ISO 8601)

For example: **2014-02-22T19:20:21+00:00**

AMP platform will support the following API:

# Group API Authentication
To make requests to api, you will need to set an authorization header:

+ Basic authentication for public resources: 

    **Basic-Authorization: Basic {base 64 encoded string of "##apollo2015##" string}**

+ JSON Web Token Authentication for protected resources:

    **Authorization: Bearer {yourtokenhere}**

# Group HTTP Status Codes
When a HTTP request return error, the HTTP status codes should be in follow list:

+ Code **401**: user unauthorized or token expired.
+ Code **404**: data not found error.
+ Code **415**: Unsupported Media Type. This error will happen when user upload file is not an image.
+ Code **405**: all errors related to method synctax.
+ Code **500**: other error. This error should be attached a error message (ex: **{"message": "error message"}**).

# Group HTTP JSON Reponse
Response template:

    {
        "message": "...", // General message | String
        "errors": "...",  // Error details | Json
        "data": "..."     // Reponse data | Json/ArrayOfJson

    }
    
Ex with errors:

    {
        "message": "Could not create new user.",
        "errors": {
            "username": [
                "The username field is required."
            ],
            "password": [
                "The password field is required."
            ]
        },
        "data": " "
    }
    
Ex without errors:

    {
        "message": "User has been created.",
        "errors": null,
        "data": {
            "id": "1", 
            "name": "Loc"
        }
    }
    
# Group API Types
## Article type[type_id]
    1 = Article
    2 = Blog
    3 = Lesson
    
## Gender[gender]
    1 = Male
    2 = Female
    
## Event's status id[status_id]
    1 = Open
    2 = Closed

## User Type[user_type]
    1 = Admin
    2 = Coach
    3 = Member
    4 = Community
    
## User status id[status_id]
    1 = Published
    2 = Unpublished

## User's discussion histories type[action]
    CREATE
    ANSWER
    
## User's action action id[action_id]    
    1 = SHARE
    2 = FOLLOW (interested)
    3 = UNFOLLOW (uninterested)
    4 = RATE
    5 = JOIN
    6 = UNJOIN
    7 = HIDE
    8 = SHOW

## User's action target type id[target_type_id]
    1 = Article
    2 = Blog
    3 = Lesson
    4 = User 
    5 = Event
    6 = Recommendation
    
## My profile's recommendation state[state]
    1 = HIDE
    2 = SHOW

# Group Tags
## Tags Collection [/articles/tags]
### List all article tags [GET]
+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": [
                {"id": "1", "name": "mobile"}, 
                {"id": "2", "name": "computer"},
                {"id": "3", "name": "computer 3"},
                {"id": "4", "name": "computer 4"},
                {"id": "5", "name": "computer 5"},
                {"id": "6", "name": "computer 6"}
            ]
        }

# Group Articles
## Articles Collection [/articles/{?type_id}{?page}{?per_page}{?sort}{?order}{?tag_id}]
### List all articles [GET]
+ Parameters
    + type_id (required, String, `1` ) ... type of article. 1: Article, 2: Blog, 3: Lesson.
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    + sort (optional, string, `title` ) ... sort by field name. Ex: id, title, created_at
    + order (optional, string, `desc` ) ... Sort direction. Only allow 'desc|asc'
    + tag_id (optional, string, `mobile,pc` ) ... List of filter tag's id.
    
+ Response 200 (application/json)

        {
            "error": null, 
            "message": null, 
            "data": [
                {
                    "id": "1", 
                    "title": "title 2", 
                    "summary": "summary 1", 
                    "thumb": "http://img.gettyimageslatam.com/public/userfiles/redesign/images/landing/home/img_entry_002.jpg", 
                    "share_count": 100, 
                    "view_count": 120, 
                    "rating_average": 3.5, 
                    "rating_count": 120,
                    "comment_count": 100, 
                    "type_id": 1,
                    "created_at": "2014-02-23T19:20+00:00",
                    "tags": [
                        {"id": 2, "name": "computer"}
                    ]
                },
                {
                    "id": "2", 
                    "title": "title 2", 
                    "summary": "summary 1", 
                    "thumb": "http://img.gettyimageslatam.com/public/userfiles/redesign/images/landing/home/img_entry_002.jpg", 
                    "share_count": 100, 
                    "view_count": 120, 
                    "rating_average": 4.5, 
                    "rating_count": 120,
                    "comment_count": 100, 
                    "type_id": 1,
                    "created_at": "2014-02-23T15:20+00:00",
                    "tags": [
                        {"id": 2, "name": "computer"}
                    ]
                },
                {
                    "id": "3", 
                    "title": "title 3", 
                    "summary": "summary 1", 
                    "thumb": "http://img.gettyimageslatam.com/public/userfiles/redesign/images/landing/home/img_entry_002.jpg", 
                    "share_count": 100, 
                    "view_count": 120, 
                    "rating_average": 5, 
                    "rating_count": 120,
                    "type_id": 1,
                    "comment_count": 100, 
                    "created_at": "2014-02-22T19:20+00:00",
                    "tags": [
                        {"id": 2, "name": "computer"}
                    ]
                }
            ]
        }

## Article [/articles/{articleId}]
### Get Article Detail [GET]
+ Parameters
    + articleId (string) ... ID of article.
+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": {
                    "id": 1,
                    "title": "title",
                    "summary": "summary 1",
                    "content": "html content",
                    "share_count": 100, 
                    "view_count": 120, 
                    "rating_average": 3.5, 
                    "rating_count": 120,
                    "comment_count": 100,
                    "type_id": 1,
                    "thumb": "http://img.gettyimageslatam.com/public/userfiles/redesign/images/landing/home/img_entry_002.jpg", 
                    "created_by": 1,
                    "created_at": "2014-02-22T19:20+00:00",
                    "tags": [
                        {"id": 2, "name": "computer"}
                    ],
                    "is_rated": true,
                    "has_quiz": true,
                    "has_poll": true
                }
        }

## Article [/articles/{articleId}/statistic]
### Get Article Statistic [GET]
+ Parameters
    + articleId (string) ... ID of article.
+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": {
                "id": "1",
                "share_count": 100, 
                "view_count": 120, 
                "rating_average": 3.5, 
                "rating_count": 120,
                "comment_count": 100
            }
        }
        
# Group Notes
## Notes Collection [/articles/{articleId}/notes]
### List all Article's note [GET]
+ Parameters
    + articleId (required, string) ... ID of article.
+ Response 200 (application/json)

        {
            "message": null,
            "erros": null,
            "data": {
                "id": 1, 
                "content": "Note for article 1", 
                "created_at": "2014-02-22T19:20+00:00"
            }
        }
        
### Create/Update a note [POST]
+ Request (application/json)

        {"content": "this is a note"}

+ Response 200 (application/json)

        {
            "message": "Note {id} has been submited",
            "errors": null,
            "data": {
                "id": 2, 
                "created_at": "2014-02-22T19:20+00:00"
            }
        }
        
## Note [/articles/{articleId}/notes/{noteId}]
### Delete a Note [DELETE]
+ Parameters
    + articleId (required, string) ... ID of article.
    + noteId (required, string) ... ID of note.
+ Request (application/json)
        
+ Response 200

        {
            "message": "Note {id} has been deleted",
            "errors": null,
            "data": null
        }

        
# Group Comments
## Comments Collection [/articles/{articleId}/comments]
### List all Article's comments [GET]
+ Parameters
    + articleId (required, string) ... ID of article.
+ Response 200 (application/json)

        {
            "message": null,
            "erros": null,
            "data": [
                {
                    "id": 1, 
                    "content": "comment for article 1", 
                    "parent_id": "", 
                    "created_at": "2014-02-22T19:20+00:00",
                    "created_by_user": {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    }
                },
                {
                    "id": 2, 
                    "content": "comment for article 1", 
                    "parent_id": "", 
                    "created_at": "2014-02-22T19:20+00:00",
                    "created_by_user": {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    }
                }
            ]
        }
        
### Create a comment [POST]
+ Request (application/json)

        {"content": "this is a comment", "parent_id": "1"}

+ Response 200 (application/json)

        {
            "message": "Comment {id} has been created",
            "errors": null,
            "data": {
                "id": 2, 
                "created_at": "2014-02-22T19:20+00:00"
            }
        }
        
## Comment [/articles/{articleId}/comments/{commentId}]
### Delete a comment [DELETE]
+ Parameters
    + articleId (required, string) ... ID of article.
    + commentId (required, string) ... ID of comment.
+ Request (application/json)
        
+ Response 200

        {
            "message": "Comment {id} has been deleted",
            "errors": null,
            "data": null
        }

# Group Quiz
Every question of a Quiz or a Poll has 2 type: SINGLE_CHOICE and MULTI_CHOICE.
For each question, when user select some options, we may provide an immediately feedback based on their choices.
For example:

**What are the correct actions?**

a- Action A

b- Action B

c- Action C

d- Action D

If user select Action A, the system may produce immediate feedback such as "This is not a correct action". 
The message can be in red or green, based on the feedback's status field. Right now, we support two status: 
**positive** for green color and **negative** for red color.

## Quiz [/articles/{articleId}/quizzes]
### List all question of article's quiz [GET]
+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": [
                {
                    "id": 234,
                    "type_id": 2,
                    "title": "Question 1",
                    "options": [
                        {
                            "id": 857,
                            "title": "Option 1",
                            "type": "LABEL"
                        },
                        {
                            "id": 858,
                            "title": "Option 2",
                            "type": "INPUT"
                        },
                        {
                            "id": 859,
                            "title": "Option 3",
                            "type": "INPUT"
                        },
                        {
                            "id": 860,
                            "title": "Option 4",
                            "type": "INPUT"
                        }
                    ],
                    "feedback": [
                        {
                            "id": 789,
                            "message": "Feedback for option 857,858,859",
                            "option_ids": "857,858,859",
                            "status_id": 1
                        },
                        {
                            "id": 790,
                            "message": "Feedback for option 857,858,860",
                            "option_ids": "857,858,860",
                            "status_id": 1
                        },
                        {
                            "id": 791,
                            "message": "Feedback for option 857,859,860",
                            "option_ids": "857,859,860",
                            "status_id": 2
                        }
                    ]
                },
                {
                    "id": 244,
                    "type_id": 2,
                    "title": "Question 11",
                    "options": [
                        {
                            "id": 897,
                            "title": "Option 1",
                            "type": "LABEL"
                        },
                        {
                            "id": 898,
                            "title": "Option 2",
                            "type": "INPUT"
                        },
                        {
                            "id": 899,
                            "title": "Option 3",
                            "type": "INPUT"
                        }
                    ],
                    "feedback": [
                        {
                            "id": 820,
                            "message": "Feedback for option 897,898,899",
                            "option_ids": "897,898,899",
                            "status_id": 2
                        }
                    ]
                },
                {
                    "id": 245,
                    "type_id": 2,
                    "title": "Question 12",
                    "options": [
                        {
                            "id": 900,
                            "title": "Option 1",
                            "type": "LABEL"
                        },
                        {
                            "id": 901,
                            "title": "Option 2",
                            "type": "INPUT"
                        },
                        {
                            "id": 902,
                            "title": "Option 3",
                            "type": "LABEL"
                        },
                        {
                            "id": 903,
                            "title": "Option 4",
                            "type": "LABEL"
                        },
                        {
                            "id": 904,
                            "title": "Option 5",
                            "type": "INPUT"
                        }
                    ],
                    "feedback": [
                        {
                            "id": 821,
                            "message": "Feedback for option 900,902,904",
                            "option_ids": "900,902,904",
                            "status_id": 1
                        },
                        {
                            "id": 822,
                            "message": "Feedback for option 901,902,904",
                            "option_ids": "901,902,904",
                            "status_id": 1
                        },
                        {
                            "id": 823,
                            "message": "Feedback for option 901,902,903",
                            "option_ids": "901,902,903",
                            "status_id": 2
                        },
                        {
                            "id": 824,
                            "message": "Feedback for option 900,902,903",
                            "option_ids": "900,902,903",
                            "status_id": 1
                        },
                        {
                            "id": 825,
                            "message": "Feedback for option 900,901,903",
                            "option_ids": "900,901,903",
                            "status_id": 1
                        },
                        {
                            "id": 826,
                            "message": "Feedback for option 900,901,902",
                            "option_ids": "900,901,902",
                            "status_id": 1
                        }
                    ]
                }
            ],
            "extra_data": null
        }

## Quiz Submit [/articles/{articleId}/quizzes/answers]
### submit quiz result [POST]
+ Request (application/json)

        {
            "answers[0][question_id]": 1,
            "answers[0][options][0][id]": 1,
            "answers[0][options][0][value]": "Options value" ,
            "answers[0][options][1][id]": 2,
            "answers[0][options][1][value]": "",
            "answers[1][question_id]": 2,
            "answers[1][options][0][id]": 3,
            "answers[1][options][0][value]": "Options value"
            "answers[1][options][1][id]": 3,
            "answers[1][options][1][value]": ""
        }

+ Response 200

# Group Polls
## Poll [/polls/{articleId}]
### List all question of poll [GET]
+ Response 200 (application/json)

        [
            {
            "id": "1", 
            "type": "SINGLE_CHOICE" ,
            "question": "Question 1", 
            "feedback_messages" : [
                {"option_ids": ["1", "2"], "message" : "This is not a correct answer", "status" : "positive"},
                {"option_ids": ["2"], "message" : "This is not a correct answer", "status" : "negative"}
            ],
            "option_list": [
                {"id": "1", "text": "text for quiz 1"},
                {"id": "2", "text": "text for quiz 2"},
                {"id": "3", "text": "text for quiz 3"}
            ]
            }, 
            {
            "id", "2", 
            "type": "MULTI_CHOICE" ,
            "question": "Question 2", 
            "option_list": [
                {"id": "4", "text": "text for quiz 1"},
                {"id": "5", "text": "text for quiz 2"},
                {"id": "6", "text": "text for quiz 3"},
                {"id": "7", "text": "text for quiz 3"},
            ]
            },
        ]

## Poll Submit [/polls/{articleId}/submit]
### Submit poll result [POST]
+ Request (application/json)

        [
            {
            "id": "1",
            "choices": [ 
                { "id" : "1" }
                ]
            },
            {
            "id": "2",
            "choices": [ 
                { "id" : "1" },
                { "id" : "2" }
                ]
            }
        ]

+ Response 200

## Poll Statistic [/articles/{articleId}/polls/statistic]
### Get Poll statistic [GET]
+ Response 200
    
        {
            "message": null,
            "errors": null,
            "data": [
                {
                    "id": 889,
                    "title": "Question 108",
                    "options": [
                        {
                            "id": 3527,
                            "title": "Option 1",
                            "count": 1
                        },
                        {
                            "id": 3528,
                            "title": "Option 2",
                            "count": 1
                        },
                        {
                            "id": 3529,
                            "title": "Option 3",
                            "count": 1
                        }
                    ]
                },
                {
                    "id": 890,
                    "title": "Question 109",
                    "options": [
                        {
                            "id": 3530,
                            "title": "Option 1",
                            "count": 1
                        },
                        {
                            "id": 3531,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 3532,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 3533,
                            "title": "Option 4",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 893,
                    "title": "Question 112",
                    "options": [
                        {
                            "id": 3540,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 3541,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 3542,
                            "title": "Option 3",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 898,
                    "title": "Question 117",
                    "options": [
                        {
                            "id": 3560,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 3561,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 3562,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 3563,
                            "title": "Option 4",
                            "count": 0
                        },
                        {
                            "id": 3564,
                            "title": "Option 5",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 929,
                    "title": "Question 148",
                    "options": [
                        {
                            "id": 3682,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 3683,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 3684,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 3685,
                            "title": "Option 4",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 973,
                    "title": "Question 192",
                    "options": [
                        {
                            "id": 3858,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 3859,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 3860,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 3861,
                            "title": "Option 4",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 982,
                    "title": "Question 201",
                    "options": [
                        {
                            "id": 3895,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 3896,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 3897,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 3898,
                            "title": "Option 4",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 1025,
                    "title": "Question 244",
                    "options": [
                        {
                            "id": 4067,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 4068,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 4069,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 4070,
                            "title": "Option 4",
                            "count": 0
                        },
                        {
                            "id": 4071,
                            "title": "Option 5",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 1063,
                    "title": "Question 282",
                    "options": [
                        {
                            "id": 4216,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 4217,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 4218,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 4219,
                            "title": "Option 4",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 1072,
                    "title": "Question 291",
                    "options": [
                        {
                            "id": 4253,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 4254,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 4255,
                            "title": "Option 3",
                            "count": 0
                        },
                        {
                            "id": 4256,
                            "title": "Option 4",
                            "count": 0
                        },
                        {
                            "id": 4257,
                            "title": "Option 5",
                            "count": 0
                        }
                    ]
                },
                {
                    "id": 1080,
                    "title": "Question 299",
                    "options": [
                        {
                            "id": 4290,
                            "title": "Option 1",
                            "count": 0
                        },
                        {
                            "id": 4291,
                            "title": "Option 2",
                            "count": 0
                        },
                        {
                            "id": 4292,
                            "title": "Option 3",
                            "count": 0
                        }
                    ]
                }
            ],
            "extra_data": null
        }

# Group Events
Each event has 3 states: OPEN, ONGOING, CLOSED.

## Events Collection [/events/{?page}{?per_page}{?sort}{?filter}]
### List all Events [GET]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    + sort (optional, number, `1` ) ... sort type of list. 1: Newest (last 48 hours), 2: Attendant: low to high, 3: Attendant: high to low.
    + filter (optional, string, `mobile,pc` ) ... List of filter tag's IDs.

+ Response 200 (application/json)

        {
            "error": null, 
            "message": null, 
            "data":[
                    {
                        "id": "1",
                        "name": "event name 1",
                        "thumb": "http://img.gettyimageslatam.com/public/userfiles/redesign/images/landing/home/img_entry_002.jpg",
                        "start_time": "2014-02-20T19:20+00:00",
                        "end_time": "2014-02-22T19:20+00:00",
                        "latitude": 10.000,
                        "longitude": 104.001,
                        "address": "165, hai ba trung",
                        "status_id": 1,
                        "joined": false,
                        "attendee_count": 100,
                        "interesting_count": 30,
                        "interested_count": 60
                    },
                    {
                        "id": "2",
                        "name": "event name 1 - event ongoing",
                        "thumb": "http://img.gettyimageslatam.com/public/userfiles/redesign/images/landing/home/img_entry_002.jpg",
                        "start_time": "2014-02-20T19:20+00:00",
                        "end_time": "2014-02-22T19:20+00:00",
                        "latitude": 10.000,
                        "longitude": 104.001,
                        "address": "165, hai ba trung",
                        "status_id": 1,
                        "joined": false,
                        "attendee_count": 100,
                        "interesting_count": 100,
                        "interested_count": 60
                    },
                    {
                        "id": "3",
                        "name": "event name - user joined",
                        "thumb": "http://img.gettyimageslatam.com/public/userfiles/redesign/images/landing/home/img_entry_002.jpg",
                        "start_time": "2014-02-20T19:20+00:00",
                        "end_time": "2014-02-22T19:20+00:00",
                        "latitude": 10.000,
                        "longitude": 104.001,
                        "address": "165, hai ba trung",
                        "status_id": 2,
                        "joined": true,
                        "attendee_count": 100,
                        "interesting_count": 80,
                        "interested_count": 40
                    }
                ]
        }
        
## Event [/events/{eventId}]
### Get Event's detail [GET]
+ Response 200 (application/json)

        {
            "error": null, 
            "message": null, 
            "data": {
                "id": "1",
                "detail": "event detail 123 45 6",
                "name": "event name - user joined",
                "images": [
                    "http://apollo.loc:8000/assets/images/event1.png",
                    "http://apollo.loc:8000/assets/images/event2.png",
                    "http://apollo.loc:8000/assets/images/event3.png"
                ],
                "start_time": "2014-02-20T19:20+00:00",
                "end_time": "2014-02-22T19:20+00:00",
                "latitude": 10.000,
                "longitude": 104.001,
                "address": "165, hai ba trung",
                "status_id": 1,
                "joined": false,
                "attendee_count": 100,
                "interesting_count": 40,
                "interested_count": 30
            }
        }
        
## Event [/events/{eventId}/statistic]
### Get Event's statistic [GET]
+ Response 200 (application/json)

        {
            "id": "1",
            "status_id": 1,
            "attendee_count": 100,
            "interesting_count": 100
        }

## Event's feedback [/events/{eventId}/feedback]
Event's feedback has 2 types TEXT, SINGLE_CHOICE and MULTI_CHOICE
Option's type can be **INPUT** or **LABEL**

### Get event feedback [GET]
+ Response 200 (application/json)
    
        {
            "error": null, 
            "message": null, 
            "data":
            {
                "id": 234,
                "type_id": 2,
                "title": "Question 1",
                "options": [
                    {
                        "id": 857,
                        "title": "Option 1",
                        "type": "LABEL"
                    },
                    {
                        "id": 858,
                        "title": "Option 2",
                        "type": "LABEL"
                    },
                    {
                        "id": 859,
                        "title": "Option 3",
                        "type": "LABEL"
                    },
                    {
                        "id": 860,
                        "title": "Option 4",
                        "type": "INPUT"
                    }
                ],
            }
        }
        
## Event's feedback submit [/events/{eventId}/feedback/answer]
### Submit event's feedback [POST]
+ Request (application/json)

        {
            "answers[options][0][id]": 1,
            "answers[options][0][value]": "",
            "answers[options][1][id]": 1,
            "answers[options][1][value]": "Feedback value",
        }
    
+ Response 200

        {
            "message": "Your feedback has been submited",
            "errors": null,
            "data":null
        }
        
# Group Discussions
## Discussions Collection [/discussions/{?page}{?per_page}]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    
### Get all Discussions with 2 latest messages [GET]
+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": [
                {
                    "id": 11,
                    "created_at": "2015-03-19T18:39:20+00:00",
                    "action": "ANSWER",
                    "target": {
                        "id": 1,
                        "title": "Discussion 1",
                        "description": "I'm so cute",
                        "posted_area_id": null,
                        "created_by_user": {
                            "id": 2,
                            "username": "thanhloc",
                            "email": "thanhloc@apollo.com",
                            "first_name": "Loc",
                            "last_name": "Thanh",
                            "name_title": "Mr",
                            "gender": 1,
                            "type_id": 2,
                            "job_title": "Founder of Epsilon Mobile",
                            "organization": "Epsilon Mobile",
                            "summary": "Cute!",
                            "business_interest": "Startup",
                            "interested_count": 1,
                            "recommended_count": 4,
                            "created_at": "2015-03-15T19:49:23+00:00",
                            "password_updated_at": "2015-03-19T23:38:30+00:00"
                        }
                    },
                    "comment": {
                        "id": 212,
                        "content": "Cai ret dau dong khan em bay",
                        "parent_id": null,
                        "created_at": "2015-03-19T18:39:19+00:00",
                        "target_type_id": null,
                        "created_by_user": {
                            "id": 3,
                            "username": "numnine",
                            "email": "linhpth@gmail.com",
                            "first_name": "Linh",
                            "last_name": "Tinh",
                            "name_title": "Mr",
                            "gender": 1,
                            "type_id": 2,
                            "job_title": "Web Freelancer",
                            "organization": "Freelance",
                            "summary": "Handsome!",
                            "business_interest": "Startup",
                            "interested_count": 0,
                            "recommended_count": 1,
                            "created_at": "2015-03-15T19:49:24+00:00",
                            "password_updated_at": "2015-03-19T23:29:38+00:00"
                        }
                    }
                },
                {
                    "id": 12,
                    "created_at": "2015-03-19T18:39:38+00:00",
                    "action": "ANSWER",
                    "target": {
                        "id": 1,
                        "title": "Loc's article 1",
                        "summary": "",
                        "content": "Article content 1",
                        "type_id": 1,
                        "view_count": 0,
                        "share_count": 0,
                        "comment_count": 11,
                        "rating_count": 0,
                        "rating_average": "0.0",
                        "created_at": "2015-03-15T19:49:26+00:00",
                        "thumb": "http://apollo.loc:8000/assets/images/no-image.png",
                        "tags": [
                            {
                                "id": 2,
                                "name": "Tag 2"
                            },
                            {
                                "id": 8,
                                "name": "Tag 8"
                            },
                            {
                                "id": 9,
                                "name": "Tag 9"
                            }
                        ]
                    },
                    "comment": {
                        "id": 213,
                        "content": "Test comment",
                        "parent_id": null,
                        "created_at": "2015-03-19T18:39:38+00:00",
                        "target_type_id": 1,
                        "created_by_user": {
                            "id": 3,
                            "username": "numnine",
                            "email": "linhpth@gmail.com",
                            "first_name": "Linh",
                            "last_name": "Tinh",
                            "name_title": "Mr",
                            "gender": 1,
                            "type_id": 2,
                            "job_title": "Web Freelancer",
                            "organization": "Freelance",
                            "summary": "Handsome!",
                            "business_interest": "Startup",
                            "interested_count": 0,
                            "recommended_count": 1,
                            "created_at": "2015-03-15T19:49:24+00:00",
                            "password_updated_at": "2015-03-19T23:29:38+00:00"
                        }
                    }
                },
                {
                    "id": 13,
                    "created_at": "2015-03-19T19:25:09+00:00",
                    "action": "CREATE",
                    "target": {
                        "id": 8,
                        "title": "Ha noi mua vang nhung con mua",
                        "description": "Hoa sua thoi roi",
                        "posted_area_id": 1,
                        "created_by_user": {
                            "id": 3,
                            "username": "numnine",
                            "email": "linhpth@gmail.com",
                            "first_name": "Linh",
                            "last_name": "Tinh",
                            "name_title": "Mr",
                            "gender": 1,
                            "type_id": 2,
                            "job_title": "Web Freelancer",
                            "organization": "Freelance",
                            "summary": "Handsome!",
                            "business_interest": "Startup",
                            "interested_count": 0,
                            "recommended_count": 1,
                            "created_at": "2015-03-15T19:49:24+00:00",
                            "password_updated_at": "2015-03-19T23:29:38+00:00"
                        }
                    },
                    "comment": null
                }
            ],
            "extra_data": null
        }
        
       
## Discussions Collection [/discussions]
### Create new Discussion thread [POST]
+ Request (application/json)

        {"title": "Discussion title", "description": "description"}

+ Response 200 (application/json)

        {
            "message": "Discussion with id is 6 has been created",
            "errors": null,
            "data": {
                "title": "title",
                "description": "Description"
                "id": 6
            },
            "extra_data": null
        }
        

## Discussion [/discussions/{discussionId}/messages/{?page}{?per_page}]
### Get list messages [GET]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10

+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": [
                {
                    "id": 1,
                    "content": "Admin's comment.",
                    "parent_id": null,
                    "created_at": "2015-03-15T12:32:11+00:00",
                    "created_by_user": {
                        "id": 1,
                        "username": "admin",
                        "email": "admin@apollo.com",
                        "first_name": "Admin",
                        "last_name": null,
                        "name_title": "Mr",
                        "gender": 1,
                        "type_id": 1,
                        "job_title": null,
                        "organization": null,
                        "summary": null,
                        "business_interest": null,
                        "interested_count": 0,
                        "recommended_count": 0,
                        "created_at": "2015-03-15T12:32:08+00:00"
                    }
                },
                {
                    "id": 4,
                    "content": "Loc's comment.",
                    "parent_id": null,
                    "created_at": "2015-03-15T12:32:11+00:00",
                    "created_by_user": {
                        "id": 2,
                        "username": "thanhloc",
                        "email": "thanhloc@apollo.com",
                        "first_name": "Loc",
                        "last_name": "Thanh",
                        "name_title": "Mr",
                        "gender": 1,
                        "type_id": 2,
                        "job_title": "Founder of Epsilon Mobile",
                        "organization": "Epsilon Mobile",
                        "summary": "Cute!",
                        "business_interest": "Startup",
                        "interested_count": 1,
                        "recommended_count": 4,
                        "created_at": "2015-03-15T12:32:09+00:00"
                    }
                },
                {
                    "id": 7,
                    "content": "Linh's comment.",
                    "parent_id": null,
                    "created_at": "2015-03-15T12:32:11+00:00",
                    "created_by_user": {
                        "id": 3,
                        "username": "numnine",
                        "email": "numnine@apollo.com",
                        "first_name": "Linh",
                        "last_name": "Tinh",
                        "name_title": "Mr",
                        "gender": 1,
                        "type_id": 2,
                        "job_title": "Web Freelancer",
                        "organization": "Freelance",
                        "summary": "Handsome!",
                        "business_interest": "Startup",
                        "interested_count": 1,
                        "recommended_count": 0,
                        "created_at": "2015-03-15T12:32:09+00:00"
                    }
                },
                {
                    "id": 10,
                    "content": "Thuan's comment.",
                    "parent_id": null,
                    "created_at": "2015-03-15T12:32:11+00:00",
                    "created_by_user": {
                        "id": 4,
                        "username": "minhthuan",
                        "email": "minhthuan@apollo.com",
                        "first_name": "Thuan",
                        "last_name": "Minh",
                        "name_title": "Mr",
                        "gender": 1,
                        "type_id": 3,
                        "job_title": "QC",
                        "organization": "Epsilon Mobile",
                        "summary": "Cute!",
                        "business_interest": "Test test and test",
                        "interested_count": 0,
                        "recommended_count": 0,
                        "created_at": "2015-03-15T12:32:09+00:00"
                    }
                },
                {
                    "id": 13,
                    "content": "Quyen's comment.",
                    "parent_id": null,
                    "created_at": "2015-03-15T12:32:11+00:00",
                    "created_by_user": {
                        "id": 5,
                        "username": "yenquyen",
                        "email": "yenquyen@apollo.com",
                        "first_name": "Quyen",
                        "last_name": "Tran Yen",
                        "name_title": "Ms",
                        "gender": 2,
                        "type_id": 2,
                        "job_title": "Communicator",
                        "organization": "Epsilon Mobile",
                        "summary": "Mysterious girl?",
                        "business_interest": "Communication",
                        "interested_count": 0,
                        "recommended_count": 0,
                        "created_at": "2015-03-15T12:32:10+00:00"
                    }
                }
            ],
            "extra_data": {
                "total": 5,
                "per_page": 10,
                "current_page": 1,
                "last_page": 1,
                "from": 1,
                "to": 5
            }
        }
        
        
### Create a message [POST]
+ Request (application/json)

        {"parent_id": "parent's id", "content": "message"}
    
+ Response 200

        {
            "message": "Comment with id is 198 has been created",
            "errors": null,
            "data": {
                "content": "Cai ret dau dong khan em bay",
                "created_at": "2015-03-15T18:55:25+00:00",
                "id": 198,
                "created_by_user": {
                    "id": 3,
                    "username": "numnine",
                    "email": "numnine@apollo.com",
                    "first_name": "Linh",
                    "last_name": "Tinh",
                    "name_title": "Mr",
                    "gender": 1,
                    "type_id": 2,
                    "job_title": "Web Freelancer",
                    "organization": "Freelance",
                    "summary": "Handsome!",
                    "business_interest": "Startup",
                    "interested_count": 1,
                    "recommended_count": 0,
                    "created_at": "2015-03-15T12:32:09+00:00"
                }
            },
            "extra_data": null
        }
        
## Message [/discussion/{discussionId}/messages/{messageId}]     
### Delete a message [DELETE]
+ Request (application/json)

        
    
+ Response 200

        {
            "message": "Your message has been deleted",
            "errors": null,
            "data": null,
            "extra_data": null
        }

# Group Users
3 types (MEMBER, COACH, COMMUNITY)

## Login [/login]
### Login [POST]
+ Request (application/json)
    
        {"username": "username", "password": "password"}
    
+ Response 200 (application/json)

        {
            "errors":null, 
            "message":"", 
            "data":{
                "id": "user_id",
                "type_id": 2, 
                "status_id": 1,
                "username": "username", 
                "token": "access token", 
                "expiry_in": 20160
            }
        }

## Reset password [/resetpass]
### Reset password [POST]
+ Request (application/json)
    
        {"email": "user_email"}
    
+ Response 200

        {
            "errors": null, 
            "message": "Please check your email to get link to password reset page", 
            "data": null
        }

## Change password [/changepass]
### Change password [POST]
+ Request (application/json)
    
        {"old_password": "old_password", "new_password": "new_password", "new_password_confirmation": "new_password"}
    
+ Response 200

        {
            "errors": null, 
            "message": "Your password has been changed.", 
            "data": null
        }

## Users Collection [/users/{?page}{?per_page}{?name}{?sort}{?order}]
### Get list Contacts [GET]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    + sort (optional, string, `first_name` ) ... sort by field name. Ex: id, first_name, created_at
    + order (optional, string, `desc` ) ... Sort direction. Only allow 'desc|asc'
    + name (optional, string, `loc` ) ... 
+ Response 200 (application/json)
        
        {
            "message": null,
            "data": [
                    {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100    
                    },
                    {
                        "id": 2, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100
                    },
                    {
                        "id": 1, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100
                    }
                ]
            ,
            "errors": null
        }

## User [/users/{user_id}]
### Get user's detail [GET]
+ Response 200 (application/json)

        {
            "message": null,
            "data": {
                "id": 3, 
                "type_id": 4, 
                "status_id": 1,
                "gender": 1, 
                "username": "user_name", 
                "email": "email",
                "first_name": "First name",
                "last_name": "Last name",
                "name_title": "Mr",
                "job_title": "job title", 
                "organization": "organization", 
                "created_at": "2014-02-22T19:20+00:00",
                "updated_at": "2014-02-22T19:20+00:00", 
                "is_interested": false,
                "interested_count": 100,
                "recommended": false,
                "recommended_count": 100,
                "summary": "summary",
                "business_interest": "Business interest",
                "discussion_histories":[
                    {
                        "id": 1,
                        "discussion": {
                            "id": 1,
                            "title": "title of discussion 1",
                            "description": "discription of discussion 1",
                            "type_title":"Article"
                        },
                        "action": "CREATE",
                        "created_at": "2014-02-22T19:20+00:00"
                    },
                    {
                        "id": 2,
                        "discussion": {
                            "id": 1,
                            "title": "title of discussion 1",
                            "description": "discription of discussion 1",
                            "type_title":"Discussion"
                        },
                        "comment": {
                            "id": 1,
                            "content": "content of comment"
                        },
                        "action": "ANSWER",
                        "created_at": "2014-02-22T19:20+00:00"
                    }
                ],
                "recommendations": [
                    {"id": 1, "message": "message content 1", "user_id": 1, "created_at": "2014-02-22T19:20+00:00"},
                    {"id": 2, "message": "message content 2", "user_id": 2, "created_at": "2014-02-22T19:20+00:00"}
                ]
            },
            "errors": null
        }

### Edit user's information [POST]
+ Request (application/json)
        
        {
            "first_name": "",
            "last_name": "",
            "gender": "",
            "job_title": "job title", 
            "organization": "organization", 
            "email": "email",
            "summary": "summary",
            "business_interest": "Business interest"
        }
        
+ Response 200
    
        {
            "message": null,
            "data": {
                "id": 3, 
                "type_id": 4, 
                "status_id": 1,
                "gender": 1, 
                "username": "user_name", 
                "email": "email",
                "first_name": "First name",
                "last_name": "Last name",
                "name_title": "Mr",
                "job_title": "job title", 
                "organization": "organization", 
                "created_at": "2014-02-22T19:20+00:00",  
                "updated_at": "2014-02-22T19:20+00:00", 
                "interested_count": 100,
                "recommended_count": 100,
                "summary": "summary",
                "business_interest": "Business interest"
            },
            "errors": null
        }

## Update user avatar [/users/{user_id}/avatar]
### get user avatar [GET]

+ Response 200 (image/*)

### Update user avatar [POST]
+ Request (multipart/form-data)

        {
            "avatar": ""
        }
        
+ Response 200
        
## User's discussion histories [/users/{user_id}/discussion_histories/{?page}{?per_page}{?sort}{?order}]
### Get list all user discussion histories [GET]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    + sort (optional, string, `created_at` ) ... sort by field name. Ex: id, created_at
    + order (optional, string, `desc` ) ... Sort direction. Only allow 'desc|asc'
+ Response 200 (application/json)
    
        {
            "message": null,
            "errors": null,
            "data": {
                "id": 3,
                "username": "numnine",
                "email": "linhpth@gmail.com",
                "first_name": "Linh",
                "last_name": "Tinh",
                "name_title": "Mr",
                "gender": 1,
                "type_id": 2,
                "job_title": "Web Freelancer",
                "organization": "Freelance",
                "summary": "Handsome!",
                "business_interest": "Startup",
                "interested_count": 0,
                "recommended_count": 1,
                "created_at": "2015-03-15T19:49:24+00:00",
                "password_updated_at": "2015-03-19T23:29:38+00:00",
                "is_interested": false,
                "discussion_histories": [
                    {
                        "id": 13,
                        "created_at": "2015-03-19T19:25:09+00:00",
                        "action": "CREATE",
                        "target": {
                            "id": 8,
                            "title": "Ha noi mua vang nhung con mua",
                            "description": "Hoa sua thoi roi",
                            "posted_area_id": 1,
                            "created_by_user": {
                                "id": 3,
                                "username": "numnine",
                                "email": "linhpth@gmail.com",
                                "first_name": "Linh",
                                "last_name": "Tinh",
                                "name_title": "Mr",
                                "gender": 1,
                                "type_id": 2,
                                "job_title": "Web Freelancer",
                                "organization": "Freelance",
                                "summary": "Handsome!",
                                "business_interest": "Startup",
                                "interested_count": 0,
                                "recommended_count": 1,
                                "created_at": "2015-03-15T19:49:24+00:00",
                                "password_updated_at": "2015-03-19T23:29:38+00:00"
                            }
                        },
                        "comment": null
                    },
                    {
                        "id": 12,
                        "created_at": "2015-03-19T18:39:38+00:00",
                        "action": "ANSWER",
                        "target": {
                            "id": 1,
                            "title": "Loc's article 1",
                            "summary": "",
                            "content": "Article content 1",
                            "type_id": 1,
                            "view_count": 0,
                            "share_count": 0,
                            "comment_count": 11,
                            "rating_count": 0,
                            "rating_average": "0.0",
                            "created_at": "2015-03-15T19:49:26+00:00",
                            "thumb": "http://apollo.loc:8000/assets/images/no-image.png",
                            "tags": [
                                {
                                    "id": 2,
                                    "name": "Tag 2"
                                },
                                {
                                    "id": 8,
                                    "name": "Tag 8"
                                },
                                {
                                    "id": 9,
                                    "name": "Tag 9"
                                }
                            ]
                        },
                        "comment": {
                            "id": 213,
                            "content": "Test comment",
                            "parent_id": null,
                            "created_at": "2015-03-19T18:39:38+00:00",
                            "target_type_id": 1,
                            "created_by_user": {
                                "id": 3,
                                "username": "numnine",
                                "email": "linhpth@gmail.com",
                                "first_name": "Linh",
                                "last_name": "Tinh",
                                "name_title": "Mr",
                                "gender": 1,
                                "type_id": 2,
                                "job_title": "Web Freelancer",
                                "organization": "Freelance",
                                "summary": "Handsome!",
                                "business_interest": "Startup",
                                "interested_count": 0,
                                "recommended_count": 1,
                                "created_at": "2015-03-15T19:49:24+00:00",
                                "password_updated_at": "2015-03-19T23:29:38+00:00"
                            }
                        }
                    }
                ],
                "recommendations": [
                    {
                        "id": 5,
                        "message": "Hahaha",
                        "created_at": "2015-03-18T15:10:06+00:00",
                        "created_by_user": {
                            "id": 3,
                            "username": "numnine",
                            "email": "linhpth@gmail.com",
                            "first_name": "Linh",
                            "last_name": "Tinh",
                            "name_title": "Mr",
                            "gender": 1,
                            "type_id": 2,
                            "job_title": "Web Freelancer",
                            "organization": "Freelance",
                            "summary": "Handsome!",
                            "business_interest": "Startup",
                            "interested_count": 0,
                            "recommended_count": 1,
                            "created_at": "2015-03-15T19:49:24+00:00",
                            "password_updated_at": "2015-03-19T23:29:38+00:00"
                        }
                    }
                ]
            },
            "extra_data": null
        }
        
## User's recommendations [/users/{user_id}/recommendations/{?page}{?per_page}{?sort}{?order}]
### Get list all user recommendations [GET]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    + sort (optional, string, `created_at` ) ... sort by field name. Ex: id, created_at
    + order (optional, string, `desc` ) ... Sort direction. Only allow 'desc|asc'
+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": [
                {
                    "id": 1, 
                    "message": "message content 1", 
                    "is_visible": true,
                    "created_by_user": {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    },
                    "created_at": "2014-02-22T19:20+00:00"
                },
                {
                    "id": 2, 
                    "message": "message content 2", 
                    "is_visible": true,
                    "created_by_user": {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    },
                    "created_at": "2014-02-22T19:20+00:00"
                }
            ]
        }

## Recommendation [/users/{user_id}/recommendations]         
### create/update a recommendation [POST]
Just update field in json.
+ Request (application/json)

        {"token": "user_token", "message": "message"}

+ Response 200 (application/json)

        {
            "message": null,
            "errors": null,
            "data": {"id": 1, "create_at": "2014-02-22T19:20+00:00"}
        }
        
### Delete recommendation [DELETE]
+ Request (application/json)

        {"token": "user_token"}

+ Response 200

## Group User's Action [/users/actions]
Types of user action: SHARE, FOLLOW/UNFOLLOW(other user), RATE, ATTENDANT(event), HIDE/SHOW recommendation.
### Create a user action [POST]
+ Request (application/json)

        {
            "action_id": 1,
            "action_value": "",
            "target_id": 1,
            "target_type_id": 1,
        }
        
+ Response 200

        {
            "message": "",
            "errors": null,
            "data":null
        }
        
# Group Notifications
Notification will have 3 types: USER_ACTION, NEW_ARTICLE and NEW_EVENT.
content_type: BLOG, LESSON, ARTICLE.
## Notifications Collection [/notifications]
### Get list all notifications [GET]
+ Request (application/json)
    
        {"token": "user_token"}
    
+ Response 200 (applicaion/json)

        [
            {"id", "type": "USER_ACTION", "content_id": "content_id", "conten_title": "content_title", 
            "create_at": "2014-02-22T19:20+00:00", "content_type": "BLOG"}, 
            {"id", "type": "USER_ACTION", "content_id": "content_id", "conten_title": "content_title", 
            "create_at": "2014-02-22T19:20+00:00", "content_type": "LESSON"}
        ]
        
# Group Api for My Profile
## Get My Profile [/myprofile]
### Get logined user's detail [GET]
+ Response 200 (application/json)

        {
            "message": null,
            "data": {
                "id": 3, 
                "type_id": 4, 
                "status_id": 1,
                "gender": 1, 
                "username": "user_name", 
                "email": "email",
                "first_name": "First name",
                "last_name": "Last name",
                "name_title": "Mr",
                "job_title": "job title", 
                "organization": "organization", 
                "created_at": "2014-02-22T19:20+00:00",
                "updated_at": "2014-02-22T19:20+00:00", 
                "is_interested": false,
                "interested_count": 100,
                "recommended": false,
                "recommended_count": 100,
                "summary": "summary",
                "business_interest": "Business interest",
                "discussion_histories":[
                    {
                        "id": 1,
                        "discussion": {
                            "id": 1,
                            "title": "title of discussion 1",
                            "description": "discription of discussion 1",
                            "type_title":"Article"
                        },
                        "action": "CREATE",
                        "created_at": "2014-02-22T19:20+00:00"
                    },
                    {
                        "id": 2,
                        "discussion": {
                            "id": 1,
                            "title": "title of discussion 1",
                            "description": "discription of discussion 1",
                            "type_title":"Discussion"
                        },
                        "comment": {
                            "id": 1,
                            "content": "content of comment"
                        },
                        "action": "ANSWER",
                        "created_at": "2014-02-22T19:20+00:00"
                    }
                ],
                "recommendations": [
                    {
                    "id": 1, 
                    "message": "message content 1", 
                    "created_at": "2014-02-22T19:20+00:00", 
                    "state": 1,
                    "post_to_user": {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                        }
                    },
                    {
                    "id": 2, 
                    "message": "message content 2", 
                    "created_at": "2014-02-22T19:20+00:00", 
                    "state": 2,
                    "post_to_user": {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                        }
                    }
                ], 
                "i_interested":[
                    {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    },
                    {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    }
                ],
                "interested_me":[
                    {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    },
                    {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1, 
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title"
                    }
                ]
            },
            "errors": null
        }

## "Interested to me" collection [/myprofile/interestedme]
### get user list [GET]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    + sort (optional, string, `first_name` ) ... sort by field name. Ex: id, first_name, created_at
    + order (optional, string, `desc` ) ... Sort direction. Only allow 'desc|asc'
    + name (optional, string, `loc` ) ... 
+ Response 200 (application/json)
        
        {
            "message": null,
            "data": [
                    {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100    
                    },
                    {
                        "id": 2, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100
                    },
                    {
                        "id": 1, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100
                    }
                ]
            ,
            "errors": null
        }

## "I'm interested" collection [/myprofile/interested]
### Get "I'm interested" user list [GET]
+ Parameters
    + page (optional, number, `1` ) ... Default value: 1
    + per_page (optional, number, `10` ) ... Default value: 10
    + sort (optional, string, `first_name` ) ... sort by field name. Ex: id, first_name, created_at
    + order (optional, string, `desc` ) ... Sort direction. Only allow 'desc|asc'
    + name (optional, string, `loc` ) ... 
+ Response 200 (application/json)
        
        {
            "message": null,
            "data": [
                    {
                        "id": 3, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100    
                    },
                    {
                        "id": 2, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100
                    },
                    {
                        "id": 1, 
                        "type_id": 4, 
                        "status_id": 1,
                        "gender": 1,
                        "username": "user_name", 
                        "email": "email",
                        "first_name": "First name",
                        "last_name": "Last name",
                        "name_title": "Mr",
                        "job_title": "job title", 
                        "organization": "organization", 
                        "created_at": "2014-02-22T19:20+00:00", 
                        "interested_count": 100,
                        "recommended_count": 100
                    }
                ]
            ,
            "errors": null
        }